### ISSUE TITLE
aplicação Web

### ISSUE THREAD

**Issue by dutraneto** [thiagobodruk/discipulado#1]
Olá Thiago, me interesso por trabalhos como esse seu.
Gostei muito da ideia.
O que vc tem relacionado a ele?
Tem algo implementado já?
Posso colaborar em algo?

**Comment by thiagobodruk** [comment]
Este projeto estava rodando em produção até mês passado, ultrapassando 75.000 downloads no Google Play. Infelizmente eu precisei tirar do ar devido aos custos de hosting e servidor, que até então eram bancados por mim.
